DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS personalities;

CREATE TABLE users (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "USERNAME" TEXT UNIQUE NOT NULL,
  "PASSWORD" TEXT NOT NULL
);

CREATE TABLE chats (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "USER_ID" INTEGER NOT NULL,
  "PERSONALITY_ID" INTEGER NOT NULL,
  "MESSAGES" TEXT NOT NULL,
  UNIQUE ("USER_ID", "PERSONALITY_ID"),
  FOREIGN KEY ("USER_ID") REFERENCES users (id),
  FOREIGN KEY ("PERSONALITY_ID") REFERENCES personalities ("ID")
);

CREATE TABLE personalities (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  SYSTEM_PROMPT TEXT NOT NULL, 
  INTRO_MESSAGE TEXT NOT NULL DEFAULT ('Hi!'), 
  IMAGE_PATH TEXT NOT NULL DEFAULT ('TestImage.jpeg')
);